markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true
  auto_link: true
# markdown: redcarpet
# redcarpet:
#   extensions:
#     - autolink
highlighter: rouge
theme: null
title: 好软分享
encoding: utf-8

exclude:
  - LICENSE.txt
  # - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Read
  - UpdateLog